-- ============================================================================
-- Migration: 004_seed.sql
-- Description: Minimal seed data for development / demo
-- Run manually: `psql $DATABASE_URL -f migrations/004_seed.sql`
-- ============================================================================

-- Create a test user (replace with your Supabase test user's UUID)
-- The actual user is created via Supabase Auth sign-up.
-- This file only seeds categories and tags after a user is created.

-- ── Example: create a demo user (comment out in production) ───────────────────
-- INSERT INTO public.users (id, email, name)
-- VALUES ('00000000-0000-0000-0000-000000000001', 'demo@recall.app', 'Demo User')
-- ON CONFLICT DO NOTHING;

-- ── Default categories ───────────────────────────────────────────────────────
-- These will be upserted per user when they first use the app.

-- INSERT INTO public.categories (user_id, name, color)
-- VALUES
--     ('00000000-0000-0000-0000-000000000001', 'AI & ML', '#8b5cf6'),
--     ('00000000-0000-0000-0000-000000000001', 'Productivity', '#10b981'),
--     ('00000000-0000-0000-0000-000000000001', 'Design', '#ec4899'),
--     ('00000000-0000-0000-0000-000000000001', 'Business', '#f59e0b'),
--     ('00000000-0000-0000-0000-000000000001', 'Tech', '#3b82f6')
-- ON CONFLICT DO NOTHING;

-- ── Example items with embeddings ───────────────────────────────────────────
-- For demo purposes only. Embeddings should be generated by the AI pipeline.
-- Replace with real content from your saved items.

-- INSERT INTO public.items (user_id, platform, url, title, text, author, author_handle, saved_at)
-- VALUES
--     (
--         '00000000-0000-0000-0000-000000000001',
--         'twitter',
--         'https://x.com/example/status/123',
--         'Thread: Building a second brain with AI',
--         'A thread about using AI to build a personal knowledge management system...',
--         'Tech Writer',
--         '@techwriter',
--         now() - interval '3 days'
--     )
-- ON CONFLICT DO NOTHING;

-- ── Stats view for dashboard ──────────────────────────────────────────────────

CREATE OR REPLACE VIEW public.user_stats AS
SELECT
    user_id,
    count(*)                                           AS total_items,
    count(*) FILTER (WHERE is_favorite)               AS total_favorites,
    count(*) FILTER (WHERE is_archived)               AS total_archived,
    count(*) FILTER (WHERE platform = 'twitter')      AS twitter_count,
    count(*) FILTER (WHERE platform = 'youtube')      AS youtube_count,
    count(*) FILTER (WHERE platform = 'reddit')       AS reddit_count,
    count(*) FILTER (WHERE platform = 'instagram')    AS instagram_count,
    count(DISTINCT category_id)                        AS total_categories,
    count(DISTINCT (SELECT tag_id FROM item_tags WHERE item_tags.item_id = items.id)) AS total_tags,
    max(saved_at)                                      AS last_saved_at
FROM items
GROUP BY user_id;

-- Guard grant for Supabase free tier
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'supabase_service_role') THEN
        GRANT SELECT ON public.user_stats TO supabase_service_role;
    END IF;
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticated') THEN
        GRANT SELECT ON public.user_stats TO authenticated;
    END IF;
END
$$;